config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :templates
      resources :domains
      resources :pages, except: [ :destroy ]
      resources :form_fields
      resources :transcriptions, except: [ :destroy ]

      root to: "users#index"
    end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  resources :templates, only: [ :index, :show ] do
    resources :pages, only: [ :index, :create, :new ]
  end

  resources :pages, only: [ :show ] do
    resources :form_fields, only: [ :index ]
  end

  resources :form_fields, only: [ :show, :edit, :update, :destroy ]
  resources :transcriptions, only: [ :index ]

  authenticated :user do
    root to: "dashboard#show", as: :user_root
  end

  get "/demo", to: "home#demo"

  root to: "dashboard#show"

  resources :api_tokens, only: [ :index, :show, :new, :create, :destroy ]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resource :me, controller: :me
      resources :templates, only: [ :show ] do
        get :find_by_domain, on: :collection
      end
      resources :pages, only: [] do
        resources :transcriptions, only: [ :create ]
      end
      resources :transcriptions, only: [ :show, :index ] do
        member do
          post :generate_completion
        end
      end
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def show
    @transcriptions_count = current_user.transcriptions.count
  end
end

app/views/dashboard/show.html.erb
<div class="container mx-auto p-4">
  <div class="my-8">
    <div class="mx-auto max-w-7xl px-6 lg:px-8">
      <div class="mx-auto max-w-2xl lg:mx-0">
        <h1 class="text-3xl font-bold tracking-tight text-gray-700 sm:text-4xl">MediSpeak</h1>
        <p class="mt-3 text-base leading-7 text-gray-600">Your one-stop hub for managing real-time transcriptions.</p>
      </div>
      <div class="mx-auto mt-10 flex max-w-2xl flex-col gap-8 lg:mx-0 lg:mt-20 lg:max-w-none lg:flex-row lg:items-end">
        <%= link_to demo_path, data: { turbo: false } do %>
          <div class="hover:scale-110 ease-out duration-300 flex flex-col-reverse justify-between gap-x-16 gap-y-8 rounded-2xl bg-gray-900 p-8 sm:flex-row-reverse sm:items-end lg:w-full lg:max-w-sm lg:flex-auto lg:flex-col lg:items-start lg:gap-y-44">
            <p class="flex-none text-7xl font-bold tracking-tight text-white">Try it!</p>
            <div class="sm:w-80 sm:shrink lg:w-auto lg:flex-none">
              <p class="text-lg font-semibold tracking-tight text-white">Ready to dive in?</p>
              <p class="mt-2 text-base leading-7 text-gray-400">Explore the future of medical communication with MediSpeak! Our demo page gives healthcare professionals a hands-on experience to manage real-time transcriptions seamlessly. Don't miss the opportunity to simplify your patient conversations.
              </p>
            </div>
          </div>
        <% end %>
        <%= link_to transcriptions_path do %>
          <div class="hover:scale-110 ease-out duration-300 flex flex-col-reverse justify-between gap-x-16 gap-y-8 rounded-2xl bg-indigo-600 p-8 sm:w-11/12 sm:max-w-xl sm:flex-row-reverse sm:items-end lg:w-full lg:max-w-none lg:flex-auto lg:flex-col lg:items-start lg:gap-y-28">
            <p class="flex-none text-7xl font-bold tracking-tight text-white"><%= @transcriptions_count %></p>
            <div class="sm:w-80 sm:shrink lg:w-auto lg:flex-none">
              <p class="text-lg font-semibold tracking-tight text-white">View Transcriptions this month</p>
              <p class="mt-2 text-base leading-7 text-indigo-200">See the list of transcriptions that have been done this month</p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>