config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :templates
      resources :domains
      resources :pages, except: [ :destroy ]
      resources :form_fields
      resources :transcriptions, except: [ :destroy ]

      root to: "users#index"
    end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  resources :templates, only: [ :index, :show ] do
    resources :pages, only: [ :index, :create, :new ]
  end

  resources :pages, only: [ :show ] do
    resources :form_fields, only: [ :index ]
  end

  resources :form_fields, only: [ :show, :edit, :update, :destroy ]
  resources :transcriptions, only: [ :index ]

  authenticated :user do
    root to: "dashboard#show", as: :user_root
  end

  get "/demo", to: "home#demo"

  root to: "dashboard#show"

  resources :api_tokens, only: [ :index, :show, :new, :create, :destroy ]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resource :me, controller: :me
      resources :templates, only: [ :show ] do
        get :find_by_domain, on: :collection
      end
      resources :pages, only: [] do
        resources :transcriptions, only: [ :create ]
      end
      resources :transcriptions, only: [ :show, :index ] do
        member do
          post :generate_completion
        end
      end
    end
  end
end

app/models/form_field.rb
class FormField < ApplicationRecord
  belongs_to :page

  # Using string enum for better readability
  enum field_type: {
    string: "string",           # Text input
    number: "number",           # Numeric input
    boolean: "boolean",         # Yes/No values
    single_select: "single_select",   # Single choice from options
    multi_select: "multi_select"      # Multiple choices from options
  }

  validates :title, presence: true
  validates :friendly_name, presence: true
  validates :field_type, presence: true
  validate :validate_select_options
  validate :validate_number_constraints

  # Virtual attribute for enum options
  attr_writer :enum_options_raw

  def enum_options_raw
    @enum_options_raw || enum_options&.join("\n")
  end

  before_validation :process_enum_options

  def to_json_schema_for_ai
    schema = {
      type: json_schema_type,
      description: description
    }

    case field_type
    when "single_select", "multi_select"
      schema[:enum] = enum_options if enum_options.present?
    when "number"
      schema[:minimum] = minimum if minimum.present?
      schema[:maximum] = maximum if maximum.present?
    end

    schema.compact
  end

  private

  def json_schema_type
    case field_type
    when "single_select"
      "string"
    when "multi_select"
      "array"
    else
      field_type
    end
  end

  def validate_select_options
    return unless [ "single_select", "multi_select" ].include?(field_type)

    if enum_options.blank? || enum_options.any?(&:blank?)
      errors.add(:enum_options, "must have at least one non-empty option for select fields")
    end
  end

  def validate_number_constraints
    return unless field_type == "number"

    if minimum.present? && maximum.present? && maximum.to_f < minimum.to_f
      errors.add(:maximum, "must be greater than minimum")
    end
  end

  def process_enum_options
    return unless @enum_options_raw.present?

    # Split by newlines, remove empty lines and whitespace
    self.enum_options = @enum_options_raw
      .split("\n")
      .map(&:strip)
      .reject(&:blank?)
      .uniq
  end
end

app/controllers/admin/form_fields_controller.rb
module Admin
  class FormFieldsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/form_fields_controller.rb
class FormFieldsController < ApplicationController
  before_action :set_form_field, only: [ :show, :edit, :update, :destroy ]
  after_action :verify_authorized
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # GET /pages/1/form_fields
  def index
    @page = Page.find(params[:page_id])
    @pagy, @form_fields = pagy(@page.form_fields.sort_by_params(params[:sort], sort_direction))

    authorize @form_fields
  end

  # GET /form_fields/1 or /form_fields/1.json
  def show
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_form_field
    @form_field = FormField.find(params[:id])

    authorize @form_field
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/views/form_fields/_form.html.erb
<%= form_with(model: form_field.persisted? ? form_field : [@page, form_field] ) do |form| %>
  <%= render "shared/error_messages", resource: form.object %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :metadata %>
    <%= form.text_area :metadata, class: "form-control" %>
  </div>
  <div>
    <%= form.button button_text(form.send(:submit_default_value)), class: "btn btn-primary" %>
    <% if form.object.new_record? %>
      <%= link_to t("cancel"), page_path(@page), class: "btn btn-white" %>
    <% else %>
      <%= link_to t("cancel"), form_field_path(@form_field), class: "btn btn-white" %>
    <% end %>
  </div>
<% end %>

app/views/form_fields/_index.html.erb
<div id="<%= dom_id(form_field, :index) %>" class="bg-white rounded-md shadow p-6">
  <%= turbo_stream_from form_field %>
  <%= render form_field %>
  <%= link_to "View", form_field, class: "btn btn-white" %>
</div>

app/views/form_fields/index.html.erb
<%= content_for :title, "Form Fields" %>
<%= turbo_stream_from :form_fields %>
<div class="container px-4 mx-auto my-8">
  <div class="flex items-center justify-between mb-4">
    <div>
      <h1 class="h3">Form Fields</h1>
      <div class="text-sm font-medium">
        <span class="text-gray-500">Sort by:</span>
        <%= sortable @form_fields, :title, "Title", class: "text-gray-700 mr-1" %>
        <%= sortable @form_fields, :description, "Description", class: "text-gray-700 mr-1" %>
        <%= sortable @form_fields, :page_id, "Page", class: "text-gray-700 mr-1" %>
      </div>
    </div>
    <%= link_to t("shared.scaffold.new.title", model: "Form Field"), new_page_form_field_path(@page), class: "btn btn-white" %>
  </div>
  <%= tag.div id: ("form_fields" if first_page?), class: "space-y-6" do %>
    <%= render partial: "form_fields/index", collection: @form_fields, as: :form_field, cached: true %>
    <div class="hidden only:flex flex-col items-center justify-between lg:flex-row">
      <%= image_tag "empty.svg", class: "mb-4 lg:w-1/2" %>
      <div class="flex-1 text-center">
        <p class="mb-4 h3">Create your first Form Field</p>
        <%= link_to t("shared.scaffold.new.title", model: "Form Field"), new_page_form_field_path(@page), class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
  <% if @pagy.pages > 1 %>
    <div class="my-6 text-center">
      <%== pagy_nav(@pagy) %>
    </div>
  <% end %>
</div>

app/views/form_fields/show.html.erb
<%= content_for :title, "Form Fields ##{@form_field.id}" %>
<%= turbo_stream_from @form_field %>
<div class="container px-4 mx-auto my-8">
  <div class="flex items-center justify-between mb-4">
    <h1 class="h3">
      <%= link_to @form_field.page.template.name, template_path(@form_field.page.template), class: "text-black" %>
      <span class="text-gray-400 font-light mx-2">\</span>
      <%= link_to @form_field.page.name, page_path(@form_field.page), class: "text-black" %>
      <span class="text-gray-400 font-light mx-2">\</span>
      Form Field #<%= @form_field.id %>
    </h1>
    <%= link_to t("edit"), edit_form_field_path(@form_field), class: "btn btn-white" %>
  </div>
  <div class="p-8 bg-white rounded shadow">
    <%= render @form_field %>
  </div>
</div>