config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :templates
      resources :domains
      resources :pages, except: [ :destroy ]
      resources :form_fields
      resources :transcriptions, except: [ :destroy ]

      root to: "users#index"
    end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  resources :templates, only: [ :index, :show ] do
    resources :pages, only: [ :index, :create, :new ]
  end

  resources :pages, only: [ :show ] do
    resources :form_fields, only: [ :index ]
  end

  resources :form_fields, only: [ :show, :edit, :update, :destroy ]
  resources :transcriptions, only: [ :index ]

  authenticated :user do
    root to: "dashboard#show", as: :user_root
  end

  get "/demo", to: "home#demo"

  root to: "dashboard#show"

  resources :api_tokens, only: [ :index, :show, :new, :create, :destroy ]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resource :me, controller: :me
      resources :templates, only: [ :show ] do
        get :find_by_domain, on: :collection
      end
      resources :pages, only: [] do
        resources :transcriptions, only: [ :create ]
      end
      resources :transcriptions, only: [ :show, :index ] do
        member do
          post :generate_completion
        end
      end
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-error mb-6 bg-red-500 text-white" role="alert">
    <div class="flex items-start justify-start">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" class="fill-current icon mr-4 mt-1 flex-no-shrink text-white" role="img" aria-labelledby="f1yx75u7nv0lvn6ck4z10w7lksjmk2f">
        <title id="f1yx75u7nv0lvn6ck4z10w7lksjmk2f">Icons/close outline</title>
        <path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm1.41-1.41A8 8 0 1 0 15.66 4.34 8 8 0 0 0 4.34 15.66zm9.9-8.49L11.41 10l2.83 2.83-1.41 1.41L10 11.41l-2.83 2.83-1.41-1.41L8.59 10 5.76 7.17l1.41-1.41L10 8.59l2.83-2.83 1.41 1.41z"></path>
      </svg>
      <div>
        <h4 class="font-black text-sm uppercase tracking">
          <%= I18n.t("errors.messages.not_saved", count: resource.errors.count, resource: resource.class.model_name.human.downcase) %>
        </h4>
        <ul class="">
          <% resource.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<div id="flash" class="fixed top-4 right-4 z-50 max-w-md">
  <% if notice %>
    <div class="notice bg-blue-100 border-l-4 border-blue-500 text-blue-700 p-4 mb-4 rounded shadow-md" role="alert">
      <div class="flex items-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd" />
        </svg>
        <p><%= sanitize notice %></p>
      </div>
    </div>
  <% end %>
  <% if alert %>
    <div class="notice bg-yellow-100 border-l-4 border-yellow-500 text-yellow-700 p-4 mb-4 rounded shadow-md" role="alert">
      <div class="flex items-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
        </svg>
        <p><%= sanitize alert %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="border-b border-gray-200 shadow-sm">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <%= link_to root_path, class: "flex items-center text-white" do %>
            <%= render_svg "logo", styles: "fill-current" %>
          <% end %>
        </div>
      </div>
      <div class="hidden md:block">
        <div class="ml-4 flex items-center md:ml-6">
          <% if user_signed_in? %>
            <%= link_to "API Tokens", api_tokens_path, class: "text-gray-900 hover:bg-gray-200 px-3 py-2 rounded-md text-sm font-medium" %>
            <%= button_to t(".sign_out"), destroy_user_session_path, method: :delete, class: 'text-gray-900 hover:bg-gray-200 px-3 py-2 rounded-md text-sm font-medium' %>
          <% else %>
            <%= link_to t(".log_in"), new_user_session_path, class: 'text-gray-900 hover:bg-gray-200 px-3 py-2 rounded-md text-sm font-medium' %>
            <%= link_to t(".sign_up"), new_user_registration_path, class: 'text-gray-900 hover:bg-gray-200 px-3 py-2 rounded-md text-sm font-medium' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>